const PubSubMessageTypes = {
    AUTH:{
        USER_SIGNED_UP:"AUTH_USER_SIGNED_UP",
        USER_SIGNED_IN:"AUTH_USER_SIGNED_IN",
        USER_SIGN_OUT:"AUTH_USER_SIGN_OUT",
        USER_SIGN_OUT_ALL:"AUTH_USER_SIGN_OUT_ALL",
        ACCESS_TOKEN:"AUTH_ACCESS_TOKEN",
        USER_CONFIRMED:"AUTH_USER_CONFIRMED"
    },
    POST:{
        CREATED:"POST_CREATED",
        READ:"POST_READ",
        UPDATED:"POST_UPDATED",
        DELETED:"POST_DELETED",
        TAG_CHANGED:"COMMENT_TAG_CHANGED"
    },
    COMMENT:{
        CREATED:"COMMENT_CREATED",
        READ:"COMMENT_READ",
        UPDATED:"COMMENT_UPDATED",
        DELETED:"COMMENT_DELETED",
        CONTEXT_CHANGED:"COMMENT_CONTEXT_CHANGED"
    },
    OPINION:{
        CREATED:"OPINION_CREATED",
        DELETED:"OPINION_DELETED"
    }
}

export {
    PubSubMessageTypes
}